project:
  type: book
  output-dir: docs

book:
  title: "R语言入门指南"
  author: "Shalom"
  date: "2023/8/13"
  repo-url: https://github.com/shalom-lab/r-book/
  repo-actions: [edit, issue]
  cover-image: cover.png
  chapters:
    - index.qmd
    - part: 基础篇
      chapters: 
        - text: 安装
          href: chapter/base_install.qmd
        - text: Rstudio
          href: chapter/base_rstudio.qmd
        - text: 运算符
          href: chapter/base_operator.qmd
        - text: 数据类型
          href: chapter/base_data_type.qmd
        - text: 数据框
          href: chapter/base_dataframe.qmd
        - text: R包
          href: chapter/base_package.qmd
        - text: 函数
          href: chapter/base_function.qmd
        - text: 常用函数
          href: chapter/base_common_function.qmd
        - text: 数据读写
          href: chapter/base_data_io.qmd
        - text: 向量化
          href: chapter/base_vector.qmd
    - part: 数据清理
      chapters :
        - text: tidyverse
          href: chapter/clean_tidyverse.qmd
        - text: 管道符%>%
          href: chapter/clean_pipe.qmd
        - text: 必会操作
          href: chapter/clean_dplyr.qmd
        - text: 日期处理
          href: chapter/clean_date.qmd
        - text: 字符串处理
          href: chapter/clean_string.qmd
        - text: 常用技巧
          href: chapter/clean_tips.qmd
        - text: 长宽数据转换
          href: chapter/clean_wider_longer.qmd
    - part: 数据可视化
      chapters: 
        - text: ggplot2
          href: chapter/viz_bar.qmd
    - part: 统计
      chapters: 
        - text: 基础篇
          href: chapter/stats_base.qmd
        #- text: MCMC
        #  href: chapter/stats_mcmc.qmd
        

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc-title: 目录
    df-print: paged
  pdf:
    documentclass: scrreprt

editor: source
lang: zh
comments:
  hypothesis: true
