project:
  type: book
  output-dir: docs
  pre-render: generate_global_yaml.R
execute:
  freeze: auto
book:
  title: R语言入门指南
  author: Shalom
  date: 2024/11/30
  repo-url: https://github.com/shalom-lab/r-book/
  repo-actions:
  - edit
  - issue
  cover-image: images/cover.png
  page-footer:
    center:
    - Copyright 2024, R语言与可视化
    - icon: rss
      href: https://blog.rlearner.com/
    - icon: github
      href: https://shalom-lab.github.io/r-book/
  chapters:
  - index.qmd
  - part: 基础篇
    chapters:
    - text: 安装
      href: chapter/base/install.qmd
    - text: Rstudio
      href: chapter/base/rstudio.qmd
    - text: 运算符
      href: chapter/base/operator.qmd
    - text: 数据类型
      href: chapter/base/data_type.qmd
    - text: 数据框
      href: chapter/base/dataframe.qmd
    - text: R包
      href: chapter/base/package.qmd
    - text: 函数
      href: chapter/base/function.qmd
    - text: 常用函数
      href: chapter/base/common_function.qmd
    - text: 数据读写
      href: chapter/base/data_io.qmd
    - text: 向量化
      href: chapter/base/vector.qmd
  - part: 清理篇
    chapters:
    - text: tidyverse
      href: chapter/clean/tidyverse.qmd
    - text: 管道符%>%
      href: chapter/clean/pipe.qmd
    - text: 必会操作
      href: chapter/clean/dplyr.qmd
    - text: 日期处理
      href: chapter/clean/date.qmd
    - text: 字符串处理
      href: chapter/clean/string.qmd
    - text: 常用技巧
      href: chapter/clean/tips.qmd
    - text: 长宽数据转换
      href: chapter/clean/wider_longer.qmd
format:
  html:
    theme: cosmo
    toc-title: 目录
    df-print: paged
editor: source
lang: zh
