project:
  type: book
  output-dir: docs

book:
  title: "R语言快速入门"
  author: "Shalom"
  date: "2023/8/13"
  repo-url: https://github.com/malcolmbarrett/causal-inference-in-r
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - part: 基础篇
      chapters: 
        - text: 安装
          href: chapter/base_install.qmd
        - text: Rstudio
          href: chapter/base_rstudio.qmd
        - text: 数据类型
          href: chapter/base_data_type.qmd
        - text: 函数
          href: chapter/base_function.qmd
        - text: R包
          href: chapter/base_package.qmd
        - text: 数据读写
          href: chapter/base_data_io.qmd
      
    - part: 数据清理
      chapters :
        - text: tidyverse
          href: chapter/clean_tidyverse.qmd
        - text: 必会操作
          href: chapter/clean_dplyr.qmd
        - text: 日期处理
          href: chapter/clean_date.qmd
        - text: 字符串处理
          href: chapter/clean_string.qmd
        - text: 常用技巧
          href: chapter/clean_tips.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc-title: 目录
  pdf:
    documentclass: scrreprt

editor: visual

comments:
  hypothesis: true
