part: 数据可视化
chapters:
  - text: 基础包绘图
    href: base_plot.qmd
  - text: 柱状图
    href: bar_plot.qmd
  - text: ggplot
    href: ggplot.qmd
  - text: 分面
    href: ggplot_facet.qmd
  - text: 相关矩阵
    href: correlation_plot.qmd
  - text: upset Plot
    href: upset_plot.qmd
  - text: 散点图
    href: scatter_plot.qmd
editor: visual


