# 最佳推荐-lubridate包

该包属于tidyverse组成之一,用于日期和时间处理

```{r}
#| context: setup
#| warning: false
library(tidyverse) # or library(lubridate)
```

## 基本用法

### 字符串转日期

```{r}
ymd('20221221','2023-12-21','2023/2/21','20/2/21')

mdy('12212022','12212023','12/21/2023','2/21/20')
```

### 时间间隔

```{r}
interval(ymd('2021-12-21'),ymd('20221221'))/years(1)
interval(ymd('2021-12-21'),ymd('20221221'))/months(3)
interval(ymd('2021-12-21'),ymd('20221221'))/weeks(1)
interval(ymd('2021-12-21'),ymd('20221221'))/days(1)
```

### 年月提取

```{r}
ymd('2021-12-21') %>% year()
ymd('2021-12-21') %>% month()
ymd('2021-12-21') %>% week()
ymd('2021-12-21') %>% day()
```

### 日期运算

```{r}
ymd('2021-12-21')+days(365)
ymd('2021-12-21')+weeks(52)
ymd('2021-12-21')+months(12)
ymd('2021-12-21')+years(1)

```

## 实战应用
### 年龄计算

HIS系统住院数据模拟，计算就诊年月周，就诊年龄，住院天数

```{r}
#| context: setup
data<-data.frame(id=1:6,birth_date=paste(2021,1,1:6,sep='-'),
                 admit_date=paste(2023,5:10,6:1,sep='-'),
                 disch_date=paste(2023,5:10,6:11,sep='-'))
data
```

```{r}
data %>%
  mutate(birth_date=ymd(birth_date),
         admit_date=ymd(admit_date),
         disch_date=ymd(disch_date),
         age=interval(birth_date,admit_date)/years(1),
         los=interval(admit_date,disch_date)/days(1)) %>%
  mutate(year=year(admit_date),
         month=month(admit_date),
         week=week(admit_date))
```
